import {WORLDS,LEVELS,LEVEL_BY_ID} from './levels.js';
import {createState,stepState,validateNope} from './engine.js';
const c=document.querySelector('#game'),x=c.getContext('2d');x.imageSmoothingEnabled=false;
const $=s=>document.querySelector(s), modal=$('#modal'),dpad=$('#dpad');
const P={bg:'#1a1c2c',grid:'#333c57',grid2:'#29366f',white:'#f4f4f4',sand:'#ffcd75',mint:'#38b764',ice:'#41a6f6',red:'#b13e53',gray:'#94b0c2',black:'#111018'};
let progress=JSON.parse(localStorage.getItem('ziy-progress')||'{"done":{}}'),screen='map',world=1,level=null,state=null,undo=[],lang=localStorage.getItem('ziy-lang')||'EN';
const save=()=>localStorage.setItem('ziy-progress',JSON.stringify(progress));
function fit(){let s=Math.max(1,Math.floor(Math.min((innerWidth-12)/240,(innerHeight-190)/160)));c.style.width=240*s+'px';c.style.height=160*s+'px'}addEventListener('resize',fit);fit();
function txt(t,px,py,col=P.white,sz=7,align='left'){x.fillStyle=col;x.font=`bold ${sz}px monospace`;x.textBaseline='top';x.textAlign=align;x.fillText(String(t),px,py)}
function rect(px,py,w,h,col){x.fillStyle=col;x.fillRect(px,py,w,h)}
function zero(px,py){rect(px+4,py+2,8,12,P.sand);rect(px+6,py+4,4,8,P.bg);rect(px+3,py+5,2,2,P.white);rect(px+11,py+5,2,2,P.white);rect(px+4,py+14,3,2,P.red);rect(px+9,py+14,3,2,P.red)}
function word(e){let px=e.x*16,py=32+e.y*16;rect(px+1,py+2,14,12,P.black);rect(px+2,py+3,12,10,P.grid);txt(e.text,px+8,py+6,P.white,4,'center')}
function obj(e){let px=e.x*16,py=32+e.y*16;if(e.noun==='ZERO')return zero(px,py);let col=e.noun==='FLAG'?P.mint:e.noun==='CRAB'?P.red:e.noun==='CLUMP'?P.ice:P.sand;rect(px+3,py+3,10,10,col);txt(e.value??e.noun[0],px+8,py+6,P.black,5,'center')}
function floor(e){let px=e.x*16,py=32+e.y*16;if(e.floorType==='HOLE'){rect(px+3,py+6,10,7,P.black)}else if(e.floorType==='ZONE'){rect(px+2,py+2,12,12,P.mint);rect(px+4,py+4,8,8,P.grid)}else{rect(px+3,py+3,10,10,P.gray);txt(e.label||e.weight||'',px+8,py+6,P.black,5,'center')}}
function drawMap(){rect(0,0,240,160,P.grid2);txt('ZERO IS YOU',120,8,P.sand,14,'center');txt('ISLAND MAP',120,26,P.white,7,'center');let pts=[[38,55],[112,52],[190,58],[50,112],[130,108],[202,116]];WORLDS.forEach((w,i)=>{let [px,py]=pts[i],done=LEVELS.filter(l=>l.world===w.id&&progress.done[l.id]).length;rect(px-18,py-10,36,20,[P.sand,P.mint,P.ice,'#5d275d','#ef7d57',P.red][i]);txt(i+1,px,py-5,P.black,8,'center');txt(w.name,px,py+14,P.white,5,'center');txt(done+'/10',px,py+22,P.gray,5,'center')});txt('ALL ISLANDS OPEN',120,149,P.gray,6,'center')}
function drawWorld(){rect(0,0,240,160,P.grid2);txt('< MAP',5,5,P.gray,6);let w=WORLDS[world-1];txt(w.name,120,6,P.sand,12,'center');txt(w.subtitle,120,22,P.white,5,'center');LEVELS.filter(l=>l.world===world).forEach((l,i)=>{let px=5+(i%5)*47,py=47+Math.floor(i/5)*51;rect(px,py,42,40,progress.done[l.id]?P.mint:P.bg);txt(i+1,px+5,py+5,P.white,6);txt(l.title.slice(0,10),px+21,py+15,P.white,5,'center');txt('★'.repeat(l.difficulty),px+21,py+27,P.sand,5,'center');if(l.nope)txt('NOPE',px+21,py+34,P.red,5,'center')})}
function drawGraph(){let g=level.graph;if(!g)return;for(let e of g.edges){let a=g.nodes[e.a],b=g.nodes[e.b],used=state.graphUsed.includes(e.id);x.strokeStyle=used?P.red:P.sand;x.lineWidth=2;x.beginPath();x.moveTo(a.x*16+8,32+a.y*16+8);x.lineTo(b.x*16+8,32+b.y*16+8);x.stroke()}for(let [id,n] of Object.entries(g.nodes)){rect(n.x*16+3,32+n.y*16+3,10,10,id===state.graphNode?P.ice:P.white);txt(id,n.x*16+8,32+n.y*16+5,P.black,5,'center')}}
function drawPlay(){rect(0,0,240,160,P.bg);for(let gy=0;gy<8;gy++)for(let gx=0;gx<12;gx++)rect(gx*16,32+gy*16,16,16,(gx+gy)%2?P.grid:P.grid2);if(level.mode==='graph')drawGraph();else{for(let e of state.entities.filter(e=>e.kind==='floor'))floor(e);for(let e of state.entities.filter(e=>e.kind==='object'))obj(e);for(let e of state.entities.filter(e=>e.kind==='word'))word(e)}rect(192,0,48,160,P.black);txt(level.title,216,7,P.sand,6,'center');txt('MOVES '+state.moves,216,20,P.gray,5,'center');txt('WORLD '+level.world,216,30,P.white,5,'center');if(level.nope)txt('NOPE?',216,46,P.red,7,'center');txt('↶ UNDO',216,139,P.gray,5,'center')}
function draw(){if(screen==='map')drawMap();else if(screen==='world')drawWorld();else drawPlay();requestAnimationFrame(draw)}
function controls(){dpad.classList.toggle('hidden',screen!=='play');$('#mapbtn').classList.toggle('hidden',screen!=='play');$('#nope').classList.toggle('hidden',!(screen==='play'&&level?.nope));$('#lens').classList.toggle('hidden',!(screen==='play'&&level?.lens));$('#langbtn').textContent=lang}
function load(id){level=LEVEL_BY_ID[id];state=createState(level);undo=[];screen='play';controls()}
function move(d){if(screen!=='play'||state.won)return;undo.push(structuredClone(state));state=stepState(state,level,d);if(state.won){progress.done[level.id]=1;save();setTimeout(()=>show(`<h2>LEVEL HOLDS.</h2><p>${level.title}</p><button id="ok">ISLAND</button>`),100)}}
function show(h){modal.innerHTML='<div class="modalbox">'+h+'</div>';modal.classList.remove('hidden');let b=$('#ok');if(b)b.onclick=()=>{modal.classList.add('hidden');screen='world';world=level.world;controls()}}
function nope(){if(!level?.nope)return;let v=validateNope(level);if(v.valid){progress.done[level.id]=1;save();show(`<h2>NOPE PROVED.</h2><p>${v.reason}</p><button id="ok">ISLAND</button>`)}else show('<h2>NOT YET.</h2><p>There is still a reachable solution.</p><button data-close>BACK</button>')}
function tap(ev){let r=c.getBoundingClientRect(),px=(ev.clientX-r.left)/r.width*240,py=(ev.clientY-r.top)/r.height*160;if(screen==='map'){let pts=[[38,55],[112,52],[190,58],[50,112],[130,108],[202,116]],i=pts.findIndex(([a,b])=>Math.abs(px-a)<25&&Math.abs(py-b)<28);if(i>=0){world=i+1;screen='world';controls()}}else if(screen==='world'){if(py<35){screen='map';controls();return}let col=Math.floor((px-5)/47),row=Math.floor((py-47)/51),i=row*5+col,ls=LEVELS.filter(l=>l.world===world);if(i>=0&&i<ls.length)load(ls[i].id)}}
c.addEventListener('click',tap);let p0;c.addEventListener('pointerdown',e=>p0={x:e.clientX,y:e.clientY});c.addEventListener('pointerup',e=>{if(screen!=='play'||!p0)return;let dx=e.clientX-p0.x,dy=e.clientY-p0.y;if(Math.hypot(dx,dy)>20)move(Math.abs(dx)>Math.abs(dy)?dx>0?'R':'L':dy>0?'D':'U');p0=null});
dpad.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>move(b.dataset.dir));$('#undo').onclick=()=>{if(undo.length)state=undo.pop()};$('#nope').onclick=nope;$('#mapbtn').onclick=()=>{screen='world';world=level.world;controls()};$('#lens').onclick=()=>show('<h2>INVARIANT LENS</h2><p>'+String(level.lens||level.concept).toUpperCase()+'</p><button data-close>CLOSE</button>');$('#langbtn').onclick=()=>{lang=lang==='EN'?'FR':'EN';localStorage.setItem('ziy-lang',lang);controls()};$('#soundbtn').onclick=()=>{};$('#musicbtn').onclick=()=>{};$('#parent').onclick=()=>show(`<h2>PARENT</h2><p>${Object.keys(progress.done).length}/60 levels solved. Progress stays on this device.</p><button data-close>CLOSE</button>`);modal.onclick=e=>{if(e.target.dataset.close!==undefined)modal.classList.add('hidden')};
addEventListener('keydown',e=>{let m={ArrowLeft:'L',ArrowRight:'R',ArrowUp:'U',ArrowDown:'D'};if(m[e.key]){e.preventDefault();move(m[e.key])}});
controls();draw();
