import {WORLDS,LEVELS,LEVEL_BY_ID} from './levels.js';
import {NIL_LEVELS,NIL_LEVEL_BY_ID} from './nil-levels.js';
import {createState,stepState,validateNope} from './engine.js';
import {displayFactKey} from './facts.js';
const c=document.querySelector('#game'),x=c.getContext('2d');x.imageSmoothingEnabled=false;
const $=s=>document.querySelector(s), modal=$('#modal');
const controls=$('#controls');
const P={bg:'#111827',grid:'#49603f',grid2:'#556b3f',white:'#f4f4f4',sand:'#ffd27f',mint:'#47d16c',ice:'#4bb5ff',red:'#d94b67',gray:'#a9b7cc',black:'#070910',gold:'#f7b849',rust:'#ef7d57',violet:'#a56de2',paper:'#fff0c2',deep:'#222b40'};
const baseProgress=JSON.parse(localStorage.getItem('ziy-progress')||'{"done":{}}');
let progress={version:2,...baseProgress,done:baseProgress.done||{},nilExpansion:baseProgress.nilExpansion||{enabled:true,facts:[],theoremDiscoveries:[],archiveOpen:false,telemetry:{facts_authored:0,false_fact_attempts:0,fact_variants_authored:0,fact_recalls_completed:0,theorem_uses:0,proof_rails_completed:0}}};
progress.nilExpansion.enabled=true;progress.nilExpansion.facts??=[];progress.nilExpansion.telemetry??={facts_authored:0,false_fact_attempts:0,fact_variants_authored:0,fact_recalls_completed:0,theorem_uses:0,proof_rails_completed:0};
let screen='map',world=1,level=null,state=null,undo=[],lang=localStorage.getItem('ziy-lang')||'EN';
const save=()=>localStorage.setItem('ziy-progress',JSON.stringify(progress));save();
function fit(){const portrait=innerHeight>=innerWidth||innerWidth<720;c.width=portrait?192:240;c.height=portrait?224:160;const top=$('#topbar')?.offsetHeight||0,ctrl=controls?.classList.contains('hidden')?0:(controls?.offsetHeight||0);const maxW=innerWidth-8,maxH=innerHeight-top-ctrl-18,s=Math.max(1,Math.min(maxW/c.width,maxH/c.height));c.style.width=Math.floor(c.width*s)+'px';c.style.height=Math.floor(c.height*s)+'px'}
addEventListener('resize',fit);addEventListener('orientationchange',()=>setTimeout(fit,60));fit();
function txt(t,px,py,col=P.white,sz=7,align='left'){x.fillStyle=col;x.font=`bold ${sz}px monospace`;x.textBaseline='top';x.textAlign=align;x.fillText(String(t),px,py)}
function rect(px,py,w,h,col){x.fillStyle=col;x.fillRect(px,py,w,h)}
function line(px,py,w,h,col){rect(px,py,w,h,col)}
function zero(px,py){rect(px+4,py+1,8,1,P.gold);rect(px+2,py+3,12,10,P.black);rect(px+3,py+2,10,12,P.gold);rect(px+5,py+4,6,8,'#f8ca56');rect(px+6,py+5,4,6,P.bg);rect(px+4,py+6,2,2,P.white);rect(px+10,py+6,2,2,P.white);rect(px+5,py+14,3,2,P.red);rect(px+9,py+14,3,2,P.red)}
const WORD_NUMERAL={ZERO:'0',ONE:'1',TWO:'2',THREE:'3',FOUR:'4',FIVE:'5',SIX:'6',SEVEN:'7',EIGHT:'8',NINE:'9',TEN:'10',ELEVEN:'11',TWELVE:'12',THIRTEEN:'13',FOURTEEN:'14',FIFTEEN:'15',SIXTEEN:'16',SEVENTEEN:'17',EIGHTEEN:'18',NINETEEN:'19',TWENTY:'20',THIRTY:'30',FORTY:'40',FIFTY:'50'};
function wordGlyph(t){if(WORD_NUMERAL[t])return WORD_NUMERAL[t];return {PLUS:'+',MINUS:'−',TIMES:'×',SAME:'=',IS:'IS',YOU:'YOU',WIN:'WIN',PUSH:'PUSH',STOP:'STOP',HAS:'HAS',MOD:'MOD',NOT:'NOT',EVEN:'EVEN',ODD:'ODD',PRIME:'PRIME'}[t]||t;}
function wordColor(t){if(WORD_NUMERAL[t])return P.ice;if(['PLUS','MINUS','TIMES','MOD','SAME'].includes(t))return P.gold;if(['IS','HAS'].includes(t))return P.red;if(['YOU','WIN','PUSH','STOP','EVEN','ODD','PRIME'].includes(t))return P.mint;return P.violet;}
function word(e){let px=e.x*16,py=32+e.y*16,col=wordColor(e.text),g=wordGlyph(e.text);rect(px+1,py+1,14,14,P.black);rect(px+2,py+2,12,12,col);rect(px+3,py+3,10,10,P.deep);let sz=g.length<=2?7:g.length<=4?5:4;txt(g,px+8,py+(g.length<=2?5:6),P.white,sz,'center')}
function obj(e){let px=e.x*16,py=32+e.y*16;if(e.noun==='ZERO')return zero(px,py);if(e.noun==='FLAG'){rect(px+4,py+2,2,12,P.paper);rect(px+6,py+3,7,5,P.gold);rect(px+2,py+14,8,1,P.sand);return}if(e.noun==='CRAB'){rect(px+3,py+5,10,7,P.red);rect(px+1,py+5,3,2,P.rust);rect(px+12,py+5,3,2,P.rust);rect(px+5,py+4,2,2,P.white);rect(px+9,py+4,2,2,P.white);return}let col=e.noun==='CLUMP'?P.ice:e.noun==='DOOR'?P.rust:P.sand;rect(px+2,py+2,12,12,P.black);rect(px+3,py+3,10,10,col);txt(e.value??e.noun[0],px+8,py+6,P.black,5,'center')}
function floor(e){let px=e.x*16,py=32+e.y*16;if(e.floorType==='FACT_RAIL'){rect(px,py+13,16,2,P.gold);rect(px+2,py+11,2,2,P.paper);rect(px+12,py+11,2,2,P.paper);return}if(e.floorType==='FACT_LOCK'){rect(px+2,py+2,12,13,P.black);rect(px+3,py+3,10,11,P.rust);rect(px+5,py+5,6,5,P.paper);rect(px+7,py+6,2,3,P.black);txt(e.label||'',px+8,py+11,P.gold,3,'center');return}if(e.floorType==='HOLE'){rect(px+3,py+6,10,7,P.black)}else if(e.floorType==='ZONE'){rect(px+2,py+2,12,12,P.mint);rect(px+4,py+4,8,8,P.grid)}else{rect(px+3,py+3,10,10,P.gray);txt(e.label||e.weight||'',px+8,py+6,P.black,5,'center')}}
function boardCell(gx,gy){let px=gx*16,py=32+gy*16,col=(gx+gy)%2?P.grid:P.grid2;rect(px,py,16,16,col);rect(px+2,py+2,2,1,'#75894d');rect(px+10,py+11,1,3,P.mint);rect(px+11,py+10,2,1,P.mint);rect(px+13,py+8,1,2,'#89a35e')}
function factEntry(f){return typeof f==='string'?f:(f.display||displayFactKey(f.key||''));}
function drawBookIcon(px,py){rect(px,py,18,16,P.black);rect(px+1,py+1,8,14,P.paper);rect(px+9,py+1,8,14,P.paper);rect(px+8,py+2,2,12,P.rust);line(px+3,py+4,4,1,P.rust);line(px+11,py+4,4,1,P.rust)}
function drawMap(){rect(0,0,c.width,c.height,P.deep);txt('ZERO IS YOU',c.width/2,7,P.sand,13,'center');txt('ISLAND MAP',c.width/2,24,P.white,6,'center');let portrait=c.width===192,pts=portrait?[[35,50],[96,50],[157,50],[35,101],[96,101],[157,101]]:[[38,55],[112,52],[190,58],[50,112],[130,108],[202,116]];WORLDS.forEach((w,i)=>{let [px,py]=pts[i],done=LEVELS.filter(l=>l.world===w.id&&progress.done[l.id]).length;rect(px-16,py-9,32,18,[P.sand,P.mint,P.ice,P.violet,P.rust,P.red][i]);rect(px-14,py-7,28,14,P.black);txt(i+1,px,py-6,P.white,8,'center');txt(w.name.slice(0,12),px,py+12,P.white,4,'center');txt(done+'/10',px,py+18,P.gray,4,'center')});if(portrait){drawBookIcon(32,151);txt('FACT BOOK',41,171,P.paper,5,'center');rect(113,150,48,22,P.black);rect(115,152,44,18,P.gold);rect(117,154,40,14,P.deep);txt('FACT FORGE',137,159,P.gold,5,'center');txt(progress.nilExpansion.facts.length+' FACTS OWNED',96,194,P.gray,5,'center');txt('ALL ISLANDS OPEN',96,210,P.gray,5,'center')}else txt('ALL ISLANDS OPEN',120,149,P.gray,6,'center')}
function drawWorld(){rect(0,0,c.width,c.height,P.deep);let w=WORLDS[world-1],portrait=c.width===192;txt('< MAP',5,5,P.gray,6);txt(w.name,c.width/2,6,P.sand,portrait?10:12,'center');txt(w.subtitle,c.width/2,21,P.white,5,'center');let ls=LEVELS.filter(l=>l.world===world);ls.forEach((l,i)=>{let cols=portrait?2:5,pw=portrait?88:42,ph=portrait?30:40,gap=portrait?6:5,px=portrait?5+(i%cols)*(pw+gap):5+(i%5)*47,py=portrait?40+Math.floor(i/cols)*34:47+Math.floor(i/5)*51;rect(px,py,pw,ph,progress.done[l.id]?P.mint:P.bg);rect(px+2,py+2,pw-4,ph-4,P.black);txt(i+1,px+6,py+5,P.sand,5);txt(l.title.slice(0,portrait?16:10),px+pw/2,py+13,P.white,portrait?5:4,'center');txt('◆'.repeat(l.difficulty),px+pw/2,py+21,P.gold,4,'center')});if(portrait&&world===2){rect(48,212-20,96,18,P.gold);rect(50,194,92,14,P.black);txt('NIL DOOR · FACT FORGE',96,198,P.gold,5,'center')}}
function drawNilWorld(){rect(0,0,c.width,c.height,'#171425');txt('< FARM',5,5,P.gray,6);txt('THE FACT FORGE',c.width/2,8,P.gold,10,'center');txt('TRUE STATEMENTS BECOME YOURS',c.width/2,23,P.paper,4,'center');NIL_LEVELS.forEach((l,i)=>{let y=42+i*31;rect(12,y,c.width-24,25,progress.done[l.id]?P.mint:P.deep);rect(14,y+2,c.width-28,21,P.black);txt(String(i+1).padStart(2,'0'),20,y+7,P.gold,6);txt(l.title,38,y+6,P.white,6);txt('◆'.repeat(l.difficulty),c.width-18,y+7,P.gold,4,'right')});drawBookIcon(15,204);txt(progress.nilExpansion.facts.length+' FACTS',40,208,P.paper,5);txt('BOOK',c.width-12,208,P.gray,5,'right')}
function drawFactBook(){rect(0,0,c.width,c.height,'#241a19');txt('< MAP',5,5,P.gray,6);txt('THE FACT BOOK',c.width/2,8,P.paper,10,'center');rect(9,28,c.width-18,c.height-38,P.black);rect(12,31,(c.width-26)/2,c.height-44,P.paper);rect(c.width/2+1,31,(c.width-26)/2,c.height-44,P.paper);rect(c.width/2-1,33,2,c.height-48,P.rust);let facts=progress.nilExpansion.facts||[];if(!facts.length){txt('EMPTY.',c.width/2,78,'#4a3329',7,'center');txt('WRITE A TRUE FACT',c.width/2,95,'#6b4938',5,'center');txt('IN THE FACT FORGE.',c.width/2,105,'#6b4938',5,'center')}else facts.slice(0,14).forEach((f,i)=>{let col=i<7?0:1,row=i%7,px=col?c.width/2+8:18,py=43+row*22;txt(factEntry(f).slice(0,15),px,py,'#30251e',5);txt((f.familyKey||'').startsWith('add:')?'FAMILY +':'FACT',px,py+8,'#7b5c45',3)})}
function drawGraph(){let g=level.graph;if(!g)return;for(let e of g.edges){let a=g.nodes[e.a],b=g.nodes[e.b],used=state.graphUsed.includes(e.id);x.strokeStyle=used?P.red:P.sand;x.lineWidth=2;x.beginPath();x.moveTo(a.x*16+8,32+a.y*16+8);x.lineTo(b.x*16+8,32+b.y*16+8);x.stroke()}for(let [id,n] of Object.entries(g.nodes)){rect(n.x*16+3,32+n.y*16+3,10,10,id===state.graphNode?P.ice:P.white);txt(id,n.x*16+8,32+n.y*16+5,P.black,5,'center')}}
function drawFactGlow(){for(const f of state.factScans||[]){let col=f.truth?P.paper:P.red;x.strokeStyle=col;x.lineWidth=1;for(const cell of f.cells)x.strokeRect(cell.x*16+1,32+cell.y*16+1,14,14)}}
function drawPlay(){let portrait=c.width===192;rect(0,0,c.width,c.height,P.bg);txt(level.expansion==='nil'?'FACT FORGE':level.title,5,4,level.expansion==='nil'?P.gold:P.sand,6);txt(level.title,5,14,P.white,portrait?6:5);txt('MOVES '+state.moves,c.width-5,5,P.gray,5,'right');txt('◆'.repeat(level.difficulty||1),c.width-5,15,P.gold,4,'right');for(let gy=0;gy<8;gy++)for(let gx=0;gx<12;gx++)boardCell(gx,gy);if(level.mode==='graph')drawGraph();else{for(let e of state.entities.filter(e=>e.kind==='floor'))floor(e);for(let e of state.entities.filter(e=>e.kind==='object'))obj(e);for(let e of state.entities.filter(e=>e.kind==='word'))word(e)}if(level.expansion==='nil')drawFactGlow();if(portrait){rect(0,160,192,64,P.black);line(0,160,192,2,P.gold);txt(level.expansion==='nil'?'WRITE A TRUE STATEMENT':(level.goalText||'MAKE A TRUE PATH TO WIN'),6,169,P.white,6);txt((level.concept||'').toUpperCase(),186,169,P.gray,5,'right');if(level.expansion==='nil'){txt('FACTS THIS ROOM',6,184,P.gray,4);(state.authoredInLevel||[]).slice(-2).forEach((k,i)=>txt('✓ '+displayFactKey(k).slice(0,22),8,193+i*10,P.paper,5))}else{txt('ACTIVE RULES',6,184,P.gray,5);(state.rules||[]).slice(0,2).forEach((r,i)=>txt(`${r.subject} ${r.verb} ${r.object}`,6,194+i*10,i===0?P.sand:P.white,5))}txt('SWIPE TO MOVE',186,214,P.gray,5,'right')}else{rect(192,0,48,160,P.black);txt(level.title,216,7,P.sand,6,'center');txt('MOVES '+state.moves,216,20,P.gray,5,'center');txt('WORLD '+level.world,216,30,P.white,5,'center')}}
function draw(){if(screen==='map')drawMap();else if(screen==='world')drawWorld();else if(screen==='nilworld')drawNilWorld();else if(screen==='factbook')drawFactBook();else drawPlay();requestAnimationFrame(draw)}
function setControls(){const play=screen==='play';controls.classList.toggle('hidden',!play);$('#nope').classList.toggle('hidden',!(play&&level?.nope));$('#lens').classList.toggle('hidden',!(play&&level?.lens));$('#langbtn').textContent=lang;fit()}
function getLevel(id){return LEVEL_BY_ID[id]||NIL_LEVEL_BY_ID[id]}
function load(id){level=getLevel(id);state=createState(level);undo=[];screen='play';setControls()}
function recordFact(f){if(!f.truth){progress.nilExpansion.telemetry.false_fact_attempts++;save();return false}let entry=progress.nilExpansion.facts.find(v=>v.key===f.key);if(!entry){entry={id:'fact-'+(progress.nilExpansion.facts.length+1),key:f.key,display:f.display,canonicalKey:f.familyKey,familyKey:f.familyKey,firstAuthoredSolveIndex:Object.keys(progress.done).length,lastRecalledSolveIndex:null,authoredCount:1,recalledCount:0,variantsAuthored:[f.key],conceptTags:['fact.authorship'],sourceLevels:[level.id]};progress.nilExpansion.facts.push(entry);progress.nilExpansion.telemetry.facts_authored++}else{entry.authoredCount++;if(!entry.sourceLevels.includes(level.id))entry.sourceLevels.push(level.id)}if(level.recall){entry.recalledCount++;entry.lastRecalledSolveIndex=Object.keys(progress.done).length;progress.nilExpansion.telemetry.fact_recalls_completed++}let family=progress.nilExpansion.facts.filter(v=>v.familyKey===f.familyKey);if(family.length>1)progress.nilExpansion.telemetry.fact_variants_authored=Math.max(progress.nilExpansion.telemetry.fact_variants_authored,family.length);save();return true}
let AC=null;function audio(){return AC??=new (window.AudioContext||window.webkitAudioContext)()}
function tone(freq=220,dur=.06,type='square',gain=.035){try{let a=audio(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+dur)}catch{}}
function factTrue(){tone(262,.18,'triangle');setTimeout(()=>tone(393,.16,'triangle'),45)}
function factFalse(){try{let a=audio(),b=a.createBuffer(1,a.sampleRate*.12,a.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);let s=a.createBufferSource(),f=a.createBiquadFilter(),g=a.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=350;g.gain.value=.025;s.connect(f).connect(g).connect(a.destination);s.start()}catch{}}
function move(d){if(screen!=='play'||state.won)return;undo.push(structuredClone(state));let before=new Set((state.authoredInLevel||[]));state=stepState(state,level,d);for(const f of state.factEvents||[]){recordFact(f);if(f.truth)factTrue();else factFalse()}if(state.won){progress.done[level.id]=1;save();setTimeout(()=>show(`<h2>${level.expansion==='nil'?'FACT FILED.':'LEVEL HOLDS.'}</h2><p>${level.title}</p><button id="ok">${level.expansion==='nil'?'FACT FORGE':'ISLAND'}</button>`),100)}}
function show(h){modal.innerHTML='<div class="modalbox">'+h+'</div>';modal.classList.remove('hidden');let b=$('#ok');if(b)b.onclick=()=>{modal.classList.add('hidden');if(level?.expansion==='nil')screen='nilworld';else{screen='world';world=level.world}setControls()}}
function nope(){if(!level?.nope)return;let v=validateNope(level);if(v.valid){progress.done[level.id]=1;save();show(`<h2>NOPE PROVED.</h2><p>${v.reason}</p><button id="ok">ISLAND</button>`)}else show('<h2>NOT YET.</h2><p>There is still a reachable solution.</p><button data-close>BACK</button>')}
function logicalPoint(ev){let r=c.getBoundingClientRect();return [(ev.clientX-r.left)/r.width*c.width,(ev.clientY-r.top)/r.height*c.height]}
function tap(ev){let [px,py]=logicalPoint(ev),portrait=c.width===192;if(screen==='map'){if(portrait&&py>142&&py<181&&px<80){screen='factbook';setControls();return}if(portrait&&py>142&&py<181&&px>105){screen='nilworld';setControls();return}let pts=portrait?[[35,50],[96,50],[157,50],[35,101],[96,101],[157,101]]:[[38,55],[112,52],[190,58],[50,112],[130,108],[202,116]],i=pts.findIndex(([a,b])=>Math.abs(px-a)<25&&Math.abs(py-b)<26);if(i>=0){world=i+1;screen='world';setControls()}}else if(screen==='world'){if(py<34){screen='map';setControls();return}if(portrait&&world===2&&py>188){screen='nilworld';setControls();return}let cols=portrait?2:5,pw=portrait?94:47,startY=portrait?40:47,rowH=portrait?34:51,col=Math.floor((px-5)/pw),row=Math.floor((py-startY)/rowH),i=row*cols+col,ls=LEVELS.filter(l=>l.world===world);if(i>=0&&i<ls.length)load(ls[i].id)}else if(screen==='nilworld'){if(py<34){screen='world';world=2;setControls();return}let i=Math.floor((py-42)/31);if(i>=0&&i<NIL_LEVELS.length)load(NIL_LEVELS[i].id);else if(py>196){screen='factbook';setControls()}}else if(screen==='factbook'&&py<30){screen='map';setControls()}}
c.addEventListener('click',tap);let p0;c.addEventListener('pointerdown',e=>p0={x:e.clientX,y:e.clientY,t:performance.now()});c.addEventListener('pointerup',e=>{if(screen!=='play'||!p0){p0=null;return}let dx=e.clientX-p0.x,dy=e.clientY-p0.y;if(Math.hypot(dx,dy)>18)move(Math.abs(dx)>Math.abs(dy)?dx>0?'R':'L':dy>0?'D':'U');p0=null});
$('#undo').onclick=()=>{if(undo.length)state=undo.pop()};$('#nope').onclick=nope;$('#mapbtn').onclick=()=>{screen=level?.expansion==='nil'?'nilworld':'world';if(level)world=level.world;setControls()};$('#lens').onclick=()=>show('<h2>INVARIANT LENS</h2><p>'+String(level.lens||level.concept).toUpperCase()+'</p><button data-close>CLOSE</button>');$('#langbtn').onclick=()=>{lang=lang==='EN'?'FR':'EN';localStorage.setItem('ziy-lang',lang);setControls()};$('#soundbtn').onclick=()=>{};$('#musicbtn').onclick=()=>{};$('#parent').onclick=()=>{let families=new Set(progress.nilExpansion.facts.map(f=>f.familyKey));show(`<h2>PARENT</h2><p>${Object.keys(progress.done).length}/65 rooms solved.</p><p>Fact relations authored: ${progress.nilExpansion.facts.length}<br>Fact families encountered: ${families.size}<br>Old facts reused: ${progress.nilExpansion.telemetry.fact_recalls_completed}</p><p>Progress stays on this device.</p><button data-close>CLOSE</button>`)};modal.onclick=e=>{if(e.target.dataset.close!==undefined)modal.classList.add('hidden')};
addEventListener('keydown',e=>{let m={ArrowLeft:'L',ArrowRight:'R',ArrowUp:'U',ArrowDown:'D'};if(m[e.key]){e.preventDefault();move(m[e.key])}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=5').catch(()=>{});
setControls();draw();
