let ID=0;
const W=(x,y,text)=>({id:`w${++ID}`,kind:'word',x,y,text});
const O=(x,y,noun,extra={})=>({id:`o${++ID}`,kind:'object',x,y,noun,...extra});
const F=(x,y,floorType,extra={})=>({id:`f${++ID}`,kind:'floor',x,y,floorType,...extra});
const R=(y,a,b,c)=>[W(0,y,a),W(1,y,b),W(2,y,c)];
const Z=(x=1,y=6)=>O(x,y,'ZERO');

export const WORLDS=[
  {id:1,name:'SHORE',subtitle:'COUNT · JOIN · CONSERVE',accent:'blue'},
  {id:2,name:'TEN-FRAME FARM',subtitle:'MAKE TEN · PARITY · JUMPS',accent:'green'},
  {id:3,name:'ARRAY BAY',subtitle:'ARRAYS · LINES · MACHINES',accent:'cyan'},
  {id:4,name:'MACHINE MARSH',subtitle:'INVERSE · FRACTIONS · PLACE',accent:'purple'},
  {id:5,name:'PRIME PEAKS',subtitle:'FACTORS · BALANCE · GAMES',accent:'orange'},
  {id:6,name:'INVARIANT ISLES',subtitle:'PROOF · GRAPH · BINARY',accent:'red'},
];

function base(id,world,title,concept,difficulty,extra={}){ return {id,world,title,concept,difficulty,width:12,height:8,entities:[],...extra}; }
function stmt(id,world,title,tokens,blank,candidates,concept,difficulty,extra={}){
  const l=base(id,world,title,concept,difficulty,{goal:{type:'statement'},...extra}); l.entities.push(...R(0,'ZERO','IS','YOU'),Z(3+blank,6));
  const sx=Math.max(3,Math.floor((12-tokens.length)/2)); l.sentenceStart=sx; tokens.forEach((t,i)=>{if(i!==blank)l.entities.push(W(sx+i,2,t));});
  const bx=sx+blank, correct=tokens[blank]; l.entities.push(W(bx,5,correct)); const distract=candidates.filter(t=>t!==correct),spots=[1,10,2,9]; distract.forEach((t,i)=>l.entities.push(W(spots[i],5,t))); l.entities.find(e=>e.kind==='object'&&e.noun==='ZERO').x=bx; return l;
}
function fusion(id,world,title,a,b,target,concept,difficulty,extra={}){ const l=base(id,world,title,concept,difficulty,{features:{fusion:true},goal:{type:'valueDoor',target},...extra}); l.entities.push(...R(0,'ZERO','IS','YOU'),...R(1,'CLUMP','IS','PUSH')); l.entities.push(Z(1,5),O(3,5,'CLUMP',{value:a}),O(5,5,'CLUMP',{value:b}),O(9,5,'DOOR',{target})); for(let x=0;x<12;x++){if(x<1||x>10){l.entities.push(O(x,4,'WALL'),O(x,6,'WALL'));}} return l; }
function numberLine(id,world,title,start,target,step,concept,difficulty,extra={}){ const l=base(id,world,title,concept,difficulty,{features:{numberLine:true},goal:{type:'touchWin'},axis:{y:4,startValue:extra.startValue??0,unit:extra.unit??1},...extra}); l.entities.push(...R(0,'ZERO','IS','YOU'),W(0,1,'STEP'),W(1,1,'IS'),W(2,1,step)); l.entities.push(O(start,4,'ZERO'),O(target,4,'FLAG')); l.entities.push(W(8,0,'FLAG'),W(9,0,'IS'),W(10,0,'WIN')); return l; }
function arrayLevel(id,world,title,count,cols,rows,concept,difficulty){ const l=base(id,world,title,concept,difficulty,{goal:{type:'fillZones',noun:'CRAB'},array:{cols,rows}}); l.entities.push(...R(0,'ZERO','IS','YOU'),...R(1,'CRAB','IS','PUSH')); const sx=4,sy=2,cells=[]; for(let i=0;i<count;i++){const x=sx+(i%cols),y=sy+Math.floor(i/cols);cells.push([x,y]);l.entities.push(F(x,y,'ZONE'));} cells.slice(0,-1).forEach(([x,y])=>l.entities.push(O(x,y,'CRAB'))); const [tx,ty]=cells[cells.length-1];l.entities.push(O(tx,ty+2,'CRAB'),Z(tx,ty+3)); return l; }
function machine(id,world,title,samples,op,n,concept,difficulty,candsOp=['PLUS','TIMES'],candsN=['ONE','TWO','THREE']){ const l=base(id,world,title,concept,difficulty,{goal:{type:'machineRule',op,n},machineSamples:samples}); const names={1:'ONE',2:'TWO',3:'THREE',4:'FOUR',5:'FIVE'}; l.entities.push(...R(0,'ZERO','IS','YOU'),Z(6,6),F(5,3,'SOCKET',{socket:'op'}),F(6,3,'SOCKET',{socket:'n'})); l.entities.push(W(5,5,op),W(6,5,names[n])); candsOp.filter(t=>t!==op).forEach((t,i)=>l.entities.push(W(2+i*2,5,t))); candsN.filter(t=>t!==names[n]).forEach((t,i)=>l.entities.push(W(9+i,5,t))); return l; }
function equation(id,world,title,add,right,answer,concept,difficulty,candidates=['TWO','FOUR','FIVE']){ const l=base(id,world,title,concept,difficulty,{goal:{type:'equationSocket',add,right},equation:{add,right}}); l.entities.push(...R(0,'ZERO','IS','YOU'),Z(6,6),F(6,3,'SOCKET',{socket:'box'})); candidates.forEach((t,i)=>l.entities.push(W(4+i*2,5,t))); const a=l.entities.find(e=>e.text===answer);if(a)a.x=6;return l; }
function lamps(id,world,title,initial,toggles,nope,concept,difficulty,extra={}){ const l=base(id,world,title,concept,difficulty,{goal:{type:'lamps'},lamps:initial,nope,...extra}); l.entities.push(...R(0,'ZERO','IS','YOU'),Z(5,6)); Object.keys(initial).forEach((lid,i)=>l.entities.push(O(3+i*2,2,'LAMP',{lampId:lid}))); toggles.forEach((ids,i)=>l.entities.push(F(3+i*3,5,'LEVER',{toggleIds:ids,label:String.fromCharCode(65+i)}))); return l; }
function binary(id,world,title,target,concept,difficulty){ const switches={s1:false,s2:false,s4:false,s8:false}; const l=base(id,world,title,concept,difficulty,{goal:{type:'switchSum',target},switches,switchWeights:{s1:1,s2:2,s4:4,s8:8},binaryTarget:target}); l.entities.push(...R(0,'ZERO','IS','YOU'),Z(5,6)); [1,2,4,8].forEach((v,i)=>l.entities.push(F(2+i*3,4,'SWITCH',{switchId:`s${v}`,weight:v,label:String(v)}))); return l; }
function graph(id,world,title,nodes,edges,start,nope,concept,difficulty,extra={}){ return base(id,world,title,concept,difficulty,{mode:'graph',goal:{type:'graphAllEdges'},graph:{nodes,edges,start},nope,...extra}); }
function staticNope(id,world,title,concept,difficulty,entities,extra={}){ return base(id,world,title,concept,difficulty,{entities:[...R(0,'ZERO','IS','YOU'),Z(1,6),...entities],goal:{type:'never'},nope:true,...extra}); }

export const LEVELS=[
base('s1-first-rule',1,'FIRST RULE','rules.visible',1,{entities:[...R(0,'ZERO','IS','YOU'),W(7,0,'FLAG'),W(8,0,'IS'),W(9,0,'WIN'),Z(2,5),O(9,5,'FLAG')],goal:{type:'touchWin'},shrine:true,hint:'THE TWO SENTENCES ALREADY WORK.'}),
base('s2-make-win',1,'MAKE WIN','rules.rewrite',2,{entities:[...R(0,'ZERO','IS','YOU'),W(7,0,'FLAG'),W(8,0,'IS'),W(9,3,'WIN'),Z(9,5),O(10,1,'FLAG')],goal:{type:'touchWin'},hint:'THE FLAG SENTENCE HAS A HOLE.'}),
base('s3-three-left',1,'THREE LEFT','counting.cardinality',2,{entities:[...R(0,'ZERO','IS','YOU'),...R(1,'CRAB','IS','PUSH'),Z(1,6),O(3,4,'CRAB'),O(5,4,'CRAB'),O(7,4,'CRAB'),O(4,5,'CRAB'),O(8,5,'CRAB'),F(3,2,'HOLE'),F(7,2,'HOLE')],goal:{type:'count',noun:'CRAB',target:3},countDisplay:{noun:'CRAB',target:3},hint:'THE HOLES ARE HUNGRY FOR EXACTLY TWO.'}),
fusion('s4-join',1,'JOIN',2,3,5,'addition.join',2,{hint:'PUSH ONE CLUMP INTO THE OTHER.'}),stmt('s5-same-five',1,'STILL FIVE',['FIVE','SAME','FIVE'],1,['SAME','PLUS','IS'],'conservation.count',2,{wind:true,hint:'THE WIND CHANGES WHERE. NOT HOW MANY.'}),stmt('s6-zero-joins',1,'ZERO JOINS',['FIVE','PLUS','ZERO','SAME','FIVE'],2,['ZERO','ONE','TWO'],'zero.identity',3,{hint:'ZERO IS BEING EXTREMELY HELPFUL.'}),stmt('s7-small-sum',1,'TWO AND ONE',['TWO','PLUS','ONE','SAME','THREE'],2,['ZERO','ONE','TWO'],'addition.join',2),fusion('s8-join-again',1,'JOIN AGAIN',4,1,5,'addition.join',3,{hint:'SAME TOTAL. DIFFERENT PARTS.'}),stmt('s9-zero-left',1,'ZERO FIRST',['ZERO','PLUS','SIX','SAME','SIX'],2,['FIVE','SIX','SEVEN'],'zero.identity',3),stmt('s10-five-ways',1,'FIVE AGAIN',['THREE','PLUS','TWO','SAME','FIVE'],2,['ONE','TWO','THREE'],'part-whole',3),
fusion('f1-make-ten',2,'TEN AND TWO',7,5,12,'make-ten',3,{tenFrame:true,shrine:true,hint:'WATCH WHICH DOTS COMPLETE TEN.'}),stmt('f2-missing',2,'MISSING',['EIGHT','PLUS','FIVE','SAME','THIRTEEN'],2,['THREE','FIVE','SIX'],'missing.addend',3,{hint:'THE EMPTY PLACE MUST COMPLETE THE SAME TOTAL.'}),stmt('f3-even',2,'PAIR UP',['EIGHT','IS','EVEN'],2,['EVEN','ODD','PRIME'],'parity.pairing',2,{pairing:true,hint:'CAN EVERY DOT FIND A PARTNER?'}),stmt('f4-odd',2,'ONE LEFT',['NINE','IS','ODD'],2,['EVEN','ODD','PRIME'],'parity.pairing',2,{pairing:true}),numberLine('f5-hop-two',2,'HOP TWO',2,10,'TWO','numberline.skip',3,{startValue:0,unit:1,hint:'THE STEP SENTENCE CONTROLS YOUR FEET.'}),stmt('f6-teen-backpack',2,'TEN PLUS FOUR',['TEN','PLUS','FOUR','SAME','FOURTEEN'],2,['THREE','FOUR','FIVE'],'placevalue.teen',3,{hint:'FOURTEEN WEARS TEN WITH FOUR LEFT OVER.'}),fusion('f7-make-exact-ten',2,'EXACT TEN',6,4,10,'make-ten',3,{tenFrame:true}),stmt('f8-near-double',2,'NEAR DOUBLE',['SIX','PLUS','SEVEN','SAME','THIRTEEN'],2,['SIX','SEVEN','EIGHT'],'near-doubles',3),stmt('f9-six-even',2,'SIX DANCES',['SIX','IS','EVEN'],2,['EVEN','ODD','PRIME'],'parity.pairing',3,{pairing:true}),numberLine('f10-hop-again',2,'HOP AGAIN',1,11,'TWO','numberline.skip',3,{startValue:-1,unit:1}),
arrayLevel('a1-two-by-three',3,'COURTYARD',6,3,2,'multiplication.array',3),stmt('a2-turn-array',3,'TURN IT',['THREE','TIMES','FOUR','SAME','TWELVE'],2,['THREE','FOUR','FIVE'],'multiplication.array',3,{rotateArray:true}),stmt('a3-commute',3,'SAME CROWD',['FOUR','TIMES','THREE','SAME','TWELVE'],2,['TWO','THREE','FOUR'],'multiplication.commutative',3),numberLine('a4-below-zero',3,'BASEMENT',8,2,'THREE','numberline.negative',4,{startValue:-8,unit:1,waterline:true,hint:'LEFT OF ZERO IS STILL A PLACE.'}),machine('a5-machine-plus-two',3,'MACHINE I',[[1,3],[2,4],[5,7]],'PLUS',2,'functions.induction',4,['PLUS','TIMES'],['ONE','TWO','THREE']),lamps('a6-nope-three',3,'THREE LAMPS',{l1:false,l2:false,l3:false},[['l1','l2'],['l2','l3'],['l1','l3']],true,'parity.invariant',5,{nopeReasons:['THE NUMBER OF LIT LAMPS CHANGES BY AN EVEN AMOUNT','THE LEVERS ARE TOO FAR APART','THREE IS A PRIME NUMBER'],correctReason:0,lens:'PARITY',hint:'TRY THE LEVERS. THEN ASK WHAT NEVER CHANGES.'}),arrayLevel('a7-two-by-two',3,'SMALL ARRAY',4,2,2,'multiplication.array',3),stmt('a8-two-by-six',3,'LONG ARRAY',['TWO','TIMES','SIX','SAME','TWELVE'],2,['FIVE','SIX','SEVEN'],'multiplication.array',4),machine('a9-machine-plus-three',3,'MACHINE +3',[[1,4],[2,5],[4,7]],'PLUS',3,'functions.induction',4,['PLUS','TIMES'],['TWO','THREE','FOUR']),numberLine('a10-step-four',3,'STEP FOUR',1,9,'FOUR','numberline.skip',4,{startValue:0,unit:1}),
machine('m1-machine-times-two',4,'MACHINE II',[[1,2],[3,6],[4,8]],'TIMES',2,'functions.induction',4,['PLUS','TIMES'],['ONE','TWO','THREE']),stmt('m2-rewind',4,'UN-ADD',['TWELVE','MINUS','FIVE','SAME','SEVEN'],2,['FOUR','FIVE','SIX'],'inverse.operations',3),stmt('m3-remainder',4,'THE CRUMB',['ELEVEN','MOD','THREE','SAME','TWO'],4,['ONE','TWO','THREE'],'remainders.mod',4),stmt('m4-fractions',4,'SAME PIE',['1/2','SAME','2/4'],1,['SAME','PLUS','TIMES'],'fractions.equivalent',3,{pies:true}),stmt('m5-times-zero',4,'ANNIHILATION',['SEVEN','TIMES','ZERO','SAME','ZERO'],2,['ZERO','ONE','SEVEN'],'zero.annihilator',4,{annihilation:true}),base('m6-place',4,'RIGHT OF THREE','placevalue.position',4,{entities:[...R(0,'ZERO','IS','YOU'),Z(6,6),F(5,3,'SOCKET',{socket:'tens'}),F(6,3,'SOCKET',{socket:'ones'}),W(5,5,'THREE'),W(6,5,'ZERO'),W(8,5,'ONE')],goal:{type:'placeValue',target:30},placeStation:true,hint:'POSITION IS DOING THE ARITHMETIC.'}),machine('m7-machine-plus-three',4,'MACHINE III',[[2,5],[3,6],[6,9]],'PLUS',3,'functions.composition',4,['PLUS','TIMES'],['TWO','THREE','FOUR']),stmt('m8-two-quarters',4,'TWO QUARTERS',['1/4','PLUS','1/4','SAME','1/2'],2,['1/4','1/3','1/2'],'fractions.equivalent',4,{pies:true}),stmt('m9-one-times',4,'ONE HELPS',['ONE','TIMES','NINE','SAME','NINE'],2,['EIGHT','NINE','TEN'],'identity.multiplicative',4),base('m10-place-forty',4,'RIGHT OF FOUR','placevalue.position',4,{entities:[...R(0,'ZERO','IS','YOU'),Z(6,6),F(5,3,'SOCKET',{socket:'tens'}),F(6,3,'SOCKET',{socket:'ones'}),W(5,5,'FOUR'),W(6,5,'ZERO'),W(8,5,'TWO')],goal:{type:'placeValue',target:40},placeStation:true}),
stmt('p1-prime-seven',5,'SEVEN REFUSES',['SEVEN','IS','PRIME'],2,['EVEN','ODD','PRIME'],'primes.definition',3,{shrine:true}),stmt('p2-factor-twelve',5,'RECTANGLE KEY',['THREE','TIMES','FOUR','SAME','TWELVE'],0,['TWO','THREE','FIVE'],'factors.pairs',4,{factorDoor:12}),stmt('p3-divisible',5,'FINGERPRINT',['EIGHTEEN','MOD','THREE','SAME','ZERO'],2,['TWO','THREE','FOUR'],'divisibility',4),equation('p4-both-sides',5,'BOTH SIDES',3,7,'FOUR','equality.relational',4,['TWO','FOUR','FIVE']),lamps('p5-parity-proof',5,'POOL CLOSED',{l1:true,l2:false,l3:true},[['l1','l2'],['l2','l3']],true,'parity.invariant',5,{nopeReasons:['EVERY MOVE FLIPS TWO LAMPS, SO LIT-PARITY STAYS EVEN','THE MIDDLE LAMP IS SHY','THE BOARD HAS THREE LAMPS'],correctReason:0,lens:'PARITY'}),base('p6-nim',5,'LAST CRAB','games.nim',5,{entities:[...R(0,'ZERO','IS','YOU'),Z(5,6),F(3,4,'TAKE',{amount:1,label:'1'}),F(8,4,'TAKE',{amount:2,label:'2'})],heap:7,turtleTake:1,goal:{type:'never'},nim:true,hint:'WORK BACKWARDS FROM ONE CRAB.'}),stmt('p7-prime-eleven',5,'ELEVEN TOO',['ELEVEN','IS','PRIME'],2,['EVEN','ODD','PRIME'],'primes.definition',4),stmt('p8-factor-eighteen',5,'RECTANGLE 18',['THREE','TIMES','SIX','SAME','EIGHTEEN'],2,['FIVE','SIX','SEVEN'],'factors.pairs',4),equation('p9-box-plus-five',5,'BOX PLUS FIVE',5,12,'SEVEN','equality.relational',5,['SIX','SEVEN','EIGHT']),stmt('p10-magic-row',5,'SUM FIFTEEN',['ONE','PLUS','FIVE','PLUS','NINE','SAME','FIFTEEN'],4,['EIGHT','NINE','TEN'],'magic-squares.sum',5),
binary('i1-binary-thirteen',6,'FOUR SWITCHES',13,'binary.placevalue',4),staticNope('i2-pigeonhole',6,'FIVE INTO FOUR','pigeonhole',4,[O(3,3,'CRAB'),O(4,3,'CRAB'),O(5,3,'CRAB'),O(6,3,'CRAB'),O(7,3,'CRAB'),O(3,5,'HOME'),O(5,5,'HOME'),O(7,5,'HOME'),O(9,5,'HOME')],{pigeonhole:true,nopeReasons:['FIVE CRABS CANNOT EACH GET A DIFFERENT ONE OF FOUR HOMES','CRABS DO NOT LIKE HOUSES','FOUR IS EVEN'],correctReason:0,lens:'CAPACITY'}),graph('i3-old-town',6,'OLD TOWN',{A:{x:3,y:2},B:{x:8,y:2},C:{x:3,y:6},D:{x:8,y:6}},[{id:'ab',a:'A',b:'B'},{id:'ad1',a:'A',b:'D'},{id:'ad2',a:'A',b:'D'},{id:'bc',a:'B',b:'C'},{id:'bd',a:'B',b:'D'},{id:'cd1',a:'C',b:'D'},{id:'cd2',a:'C',b:'D'}],'A',true,'graphs.euler',5,{nopeReasons:['MORE THAN TWO TOWNS HAVE ODD BRIDGE-DEGREE','THE RIVER IS TOO WET','SEVEN BRIDGES IS TOO MANY'],correctReason:0,lens:'DEGREE'}),graph('i4-one-stroke',6,'ONE STROKE',{A:{x:2,y:4},B:{x:5,y:2},C:{x:8,y:4},D:{x:5,y:6}},[{id:'ab',a:'A',b:'B'},{id:'bc',a:'B',b:'C'},{id:'cd',a:'C',b:'D'},{id:'da',a:'D',b:'A'},{id:'bd',a:'B',b:'D'}],'B',false,'graphs.euler',5,{lens:'DEGREE'}),staticNope('i5-checkerboard',6,'CUT CORNERS','coloring.invariant',5,[],{checkerboard:{x:2,y:2,w:8,h:4,missing:[[2,2],[9,5]]},nopeReasons:['EACH DOMINO COVERS ONE LIGHT AND ONE DARK SQUARE, BUT THE CUT BOARD DOES NOT BALANCE','THE BOARD IS TOO SMALL','CORNERS ARE IMPORTANT IN GENERAL'],correctReason:0,lens:'COLOR'}),stmt('i6-gnomon',6,'ODD BUILDS SQUARE',['ONE','PLUS','THREE','PLUS','FIVE','SAME','NINE'],4,['FOUR','FIVE','SIX'],'invariants.gnomon',5,{gnomon:true,hint:'THE L-SHAPES GROW BY ODD NUMBERS.'}),binary('i7-binary-ten',6,'TEN IN BINARY',10,'binary.placevalue',5),stmt('i8-clock-seven',6,'CLOCK SEVEN',['TWENTY','MOD','SEVEN','SAME','SIX'],2,['SIX','SEVEN','EIGHT'],'modular.arithmetic',5),graph('i9-triangle-tour',6,'TRIANGLE TOUR',{A:{x:3,y:5},B:{x:6,y:2},C:{x:9,y:5}},[{id:'ab',a:'A',b:'B'},{id:'bc',a:'B',b:'C'},{id:'ca',a:'C',b:'A'}],'A',false,'graphs.euler',4,{lens:'DEGREE'}),stmt('i10-four-odds',6,'FOUR ODDS',['ONE','PLUS','THREE','PLUS','FIVE','PLUS','SEVEN','SAME','SIXTEEN'],6,['SIX','SEVEN','EIGHT'],'invariants.gnomon',5,{gnomon:true})];
export const LEVEL_BY_ID=Object.fromEntries(LEVELS.map(l=>[l.id,l]));
