import {TIMING,rng32,seedFrom,distinctCells,sameCell} from '../state.js';
export const protocol={
 id:'breath-midpoint-v1', explorationId:'breath', construct:'temporal support of serial visuospatial maintenance', factor:'midSequenceFreeTime',
 metadata:{targetConstruct:'temporal support of serial visuospatial maintenance',manipulation:{factor:'midSequenceFreeTime',levels:['standard','pause-after-3']},heldConstant:['memoryLoad','gridSize','cueDuration','responseMode','itemSalience'],confoundAudit:{motor:'identical',visual:'pause not highlighted',ruleComplexity:'fixed',timing:'declared manipulation'},expectedErrorClasses:['serial-position-error','order-transposition'],exclusionRules:['cancelled trial']},
 generatePair({pairSeed,calibratedLoad,counterbalanceState=0}){const load=Math.max(3,Math.min(8,calibratedLoad)),order=counterbalanceState%2?['breath','standard']:['standard','breath'],skeleton={gridSize:5,memoryLoad:load,cueDuration:TIMING.flash,responseMode:'serial-location',pauseAfter:Math.min(3,load-1)};const trials={};for(const condition of ['standard','breath']){const seed=seedFrom(this.id,pairSeed,condition),rng=rng32(seed);trials[condition]={protocolVersion:this.id,explorationId:'breath',construct:this.construct,factor:this.factor,condition,trialSeed:seed,gridSize:5,memoryLoad:load,target:distinctCells(5,load,rng),pauseAfter:skeleton.pauseAfter,presentationTiming:{flashMs:TIMING.flash,gapMs:TIMING.gap,pauseExtraMs:condition==='breath'?TIMING.pauseExtra:0},responseMode:'serial-location'};}return{pairSeed,stimulusSkeletonId:`breath-${pairSeed}`,calibratedLoad,order,skeleton,trials};},
 score(spec,response){const serial=spec.target.map((p,i)=>sameCell(p,response[i]));return{correct:serial.every(Boolean),serialPositionResults:serial,firstErrorPosition:serial.findIndex(x=>!x)+1||null,response};},
 classifyError(spec,response){return this.score(spec,response).correct?'correct':'serial-position-error';},
 pairOutcome(records){const a=records.find(r=>r.condition==='standard'),b=records.find(r=>r.condition==='breath');return{metric:'correct',delta:(b?.correct?1:0)-(a?.correct?1:0)};},
 summarize(pairs){const v=pairs.filter(p=>p.valid);if(!v.length)return'No observations yet.';const pos=v.filter(p=>p.pairedOutcome.delta>0).length,neg=v.filter(p=>p.pairedOutcome.delta<0).length;if(pos===neg)return'No clear difference has emerged yet.';return pos>neg?'Extra time supported recall more often across the matched trials.':'Standard timing was recovered more often across the matched trials.';}
};
