import {TIMING,rng32,seedFrom,distinctCells,sameCell,shuffled} from '../state.js';
const GLYPHS=['diamond','ring','cross','hex','kite'];
export const protocol={
 id:'focus-retrocue-v1', explorationId:'focus', construct:'prioritization of information already held in visuospatial working memory', factor:'postEncodingPriorityCue',
 metadata:{targetConstruct:'prioritization of information already held in visuospatial working memory',manipulation:{factor:'postEncodingPriorityCue',levels:['neutral','target-specific']},heldConstant:['memoryLoad','gridSize','retentionDuration','responseMode','probeMode','itemSalience'],confoundAudit:{motor:'identical',visual:'cue identity differs only during declared cue phase',ruleComplexity:'fixed',timing:'total retention matched'},expectedErrorClasses:['target','other-remembered-location','empty'],exclusionRules:['cancelled trial']},
 generatePair({pairSeed,calibratedLoad,counterbalanceState=0}){const load=Math.max(3,Math.min(5,calibratedLoad)),order=counterbalanceState%2?['focus','neutral']:['neutral','focus'];const targetIndex=Math.floor(counterbalanceState/2)%load,targetRing=1+(counterbalanceState%2);const all=[];for(let r=0;r<5;r++)for(let c=0;c<5;c++)all.push({r,c});const ringCells=all.filter(p=>Math.min(2,Math.abs(p.r-2)+Math.abs(p.c-2))===targetRing),targetCandidates=shuffled(ringCells,rng32(seedFrom(this.id,pairSeed,'target-ring')));const targetByCondition={neutral:targetCandidates[0],focus:targetCandidates[1]};const skeleton={gridSize:5,memoryLoad:load,retentionMs:TIMING.retention,responseMode:'single-location',probeMode:'single-glyph',glyphs:GLYPHS.slice(0,load),targetIndex,targetRing}; const trials={};
  for(const condition of ['neutral','focus']){const seed=seedFrom(this.id,pairSeed,condition),rng=rng32(seed),target=targetByCondition[condition],rest=shuffled(all.filter(p=>!sameCell(p,target)),rng).slice(0,load-1),positions=[];let k=0;for(let i=0;i<load;i++)positions.push(i===targetIndex?target:rest[k++]);trials[condition]={protocolVersion:this.id,explorationId:'focus',construct:this.construct,factor:this.factor,condition,trialSeed:seed,gridSize:5,memoryLoad:load,objects:skeleton.glyphs.map((id,i)=>({id,location:positions[i]})),targetIndex,target:positions[targetIndex],probeGlyph:skeleton.glyphs[targetIndex],retroCue:condition==='focus'?skeleton.glyphs[targetIndex]:'neutral',presentationTiming:{flashMs:TIMING.flash,retentionMs:TIMING.retention,retroMs:TIMING.retro},responseMode:'single-location'};}
  return {pairSeed,stimulusSkeletonId:`focus-${pairSeed}`,calibratedLoad,order,skeleton,trials};},
  score(spec,response){return {correct:sameCell(spec.target,response),response};},
 classifyError(spec,response){if(sameCell(spec.target,response))return 'target';if(spec.objects.some(o=>sameCell(o.location,response)))return 'other-remembered-location';return 'empty';},
 pairOutcome(records){const a=records.find(r=>r.condition==='neutral'),b=records.find(r=>r.condition==='focus');return {metric:'correct',delta:(b?.correct?1:0)-(a?.correct?1:0)};},
 summarize(pairs){const v=pairs.filter(p=>p.valid),pos=v.filter(p=>p.pairedOutcome.delta>0).length,neg=v.filter(p=>p.pairedOutcome.delta<0).length;if(!v.length)return 'No observations yet.';if(pos===neg)return 'No clear priority benefit has emerged yet.';return pos>neg?`Prioritization helped in ${pos} of ${v.length} valid matched pairs.`:`Neutral retention was recovered more often in ${neg} of ${v.length} valid matched pairs.`;}
};
