import {TIMING,rng32,seedFrom,distinctCells,sameCell} from '../state.js';
export const protocol={
 id:'noise-manualspatial-v1',explorationId:'noise',construct:'serial visuospatial maintenance under manual-spatial interference',factor:'manualSpatialInterference',
 metadata:{targetConstruct:'interference during maintenance',manipulation:{factor:'manualSpatialInterference',levels:['quiet','two-arrow-responses']},heldConstant:['memoryLoad','gridSize','cueDuration','retentionBase','responseMode'],confoundAudit:{motor:'recall identical; interference is declared manipulation',visual:'encoding cues identical',ruleComplexity:'fixed arrow mapping',timing:'interference inserted during maintenance'},expectedErrorClasses:['serial-position-error','order-transposition'],exclusionRules:['failed interference response invalidates pair']},
 generatePair({pairSeed,calibratedLoad,counterbalanceState=0}){const load=Math.max(3,Math.min(8,calibratedLoad)),order=counterbalanceState%2?['noise','quiet']:['quiet','noise'],skeleton={gridSize:5,memoryLoad:load,cueDuration:TIMING.flash,responseMode:'serial-location',interferenceCount:2};const trials={};for(const condition of ['quiet','noise']){const seed=seedFrom(this.id,pairSeed,condition),rng=rng32(seed),arrows=Array.from({length:2},()=>rng()<.5?'left':'right');trials[condition]={protocolVersion:this.id,explorationId:'noise',construct:this.construct,factor:this.factor,condition,trialSeed:seed,gridSize:5,memoryLoad:load,target:distinctCells(5,load,rng),interferenceParameters:condition==='noise'?{count:2,arrows,deadlineMs:TIMING.deadline}:null,presentationTiming:{flashMs:TIMING.flash,gapMs:TIMING.gap,retentionMs:TIMING.noiseRetention},responseMode:'serial-location'};}return{pairSeed,stimulusSkeletonId:`noise-${pairSeed}`,calibratedLoad,order,skeleton,trials};},
 score(spec,response){const serial=spec.target.map((p,i)=>sameCell(p,response.locations?.[i]));const intOK=spec.condition!=='noise'||(response.interference||[]).every(x=>x.correct)&&(response.interference||[]).length===2;return{correct:serial.every(Boolean),serialPositionResults:serial,firstErrorPosition:serial.findIndex(x=>!x)+1||null,interferenceValid:intOK,response};},
 classifyError(spec,response){return this.score(spec,response).correct?'correct':'serial-position-error';},
 pairOutcome(records){const a=records.find(r=>r.condition==='quiet'),b=records.find(r=>r.condition==='noise');return{metric:'correct',delta:(b?.correct?1:0)-(a?.correct?1:0)};},
 summarize(pairs){const v=pairs.filter(p=>p.valid);if(!v.length)return'No valid observations yet.';const pos=v.filter(p=>p.pairedOutcome.delta>0).length,neg=v.filter(p=>p.pairedOutcome.delta<0).length;if(pos===neg)return'No clear interruption effect has emerged yet.';return neg>pos?'Interruption weakened recall more often across the matched trials.':'Quiet retention did not outperform interruption in this sample.';}
};
