(function(){'use strict';
var VERSION='2.0';
var phase=document.getElementById('phase'),grid=document.getElementById('grid'),app=document.getElementById('app'),dpad=document.getElementById('dpad'),reveal=document.getElementById('reveal');
var dist=document.getElementById('distractor')||document.getElementById('interference');
if(!phase||!grid||!app)return;
function q(sel,root){return (root||document).querySelector(sel)}
function phaseText(){return (phase.textContent||'').trim().toLowerCase()}
function isDistractor(){return !!(dist&&dist.classList.contains('on'))}
function studyMode(){if(grid.querySelector('.avatar'))return'path';if(grid.querySelector('.token,.mini-token'))return'update';if(grid.querySelector('.memory-dot'))return'span';return''}
function form(){var p=phaseText();if(isDistractor()||p==='remember'||p==='recall')return'span';if(p==='update'||p==='place')return'update';if(p==='move'||p==='commit')return'path';if(p==='study')return studyMode();return app.getAttribute('data-biy-form')||''}
function uiMode(){var p=phaseText();if(isDistractor())return'interrupt';if(p==='move'||p==='commit')return'path';if(p==='place'||p==='recall')return'tap';return'watch'}
function installDoctrine(){var welcome=document.getElementById('welcome'),card=welcome&&q('.card',welcome);if(!card||q('.biy20-doctrine',card))return;var oldRules=q('.rules',card);if(oldRules)oldRules.classList.add('biy20-legacy-rules');var doctrine=document.createElement('section');doctrine.className='biy20-doctrine';doctrine.setAttribute('aria-label','How Blind Is You works');doctrine.innerHTML='<div class="biy20-doctrine-kicker">A WORKING-MEMORY INSTRUMENT</div><div class="biy20-doctrine-title">Three forms. No hidden rules.</div><div class="biy20-law" data-law="path"><div class="biy20-law-mark">I</div><div><b>TRACE</b><span>SEE · VEIL · MOVE</span><small>Study the world. Walls and edges block you; a blocked move still counts. Movers shift after each move. Then replay the route from memory.</small></div></div><div class="biy20-law" data-law="update"><div class="biy20-law-mark">II</div><div><b>SHIFT</b><span>SEE · CHANGE IN MIND · PLACE</span><small>Hold every rune. Mentally move only the rune named by each arrow; every other rune stays fixed. Then place the final positions, one rune per cell.</small></div></div><div class="biy20-law" data-law="span"><div class="biy20-law-mark">III</div><div><b>ECHO</b><span>SEE · HOLD THROUGH NOISE · RECALL</span><small>Remember the glowing locations in order. Choose the larger orb during the interruption; it never changes the remembered sequence. Then recall the locations in order.</small></div></div><div class="biy20-axioms"><span>ONE GESTURE = ONE ACTION</span><span>NO TRICK RULES</span><span>ACCURACY BEFORE SPEED</span></div>';var firstP=q('p',card);if(firstP)firstP.insertAdjacentElement('afterend',doctrine);else card.insertBefore(doctrine,card.firstChild)}
function installVersionStamp(){document.documentElement.setAttribute('data-presentation-version',VERSION);document.body&&document.body.setAttribute('data-presentation-version',VERSION);var welcome=document.getElementById('welcome');if(!welcome)return;var walker=document.createTreeWalker(welcome,NodeFilter.SHOW_TEXT);var n;while((n=walker.nextNode())){if(/v1\.1/i.test(n.nodeValue||''))n.nodeValue=n.nodeValue.replace(/v1\.1/ig,'V2.0')}}
var oldGuide=document.getElementById('turnGuide');if(oldGuide)oldGuide.remove();var guide=document.createElement('section');guide.id='turnGuide';guide.className='turn-guide';guide.setAttribute('aria-live','polite');guide.setAttribute('aria-atomic','true');guide.innerHTML='<div class="guide-sigil" aria-hidden="true"><i></i></div><div class="guide-meta"><span id="guideForm">READY</span><span class="guide-version">v2.0</span></div><div id="guideAction" class="guide-action">WATCH ONLY</div><div id="guideTitle" class="guide-title">The board will tell you what to remember.</div><div id="guideDetail" class="guide-detail">Nothing is hidden. Act only when the instruction changes.</div><div id="guideSteps" class="guide-steps" aria-hidden="true"><i></i><i></i><i></i></div>';var top=q('.topbar');top.parentNode.insertBefore(guide,top.nextSibling);var guideForm=q('#guideForm'),action=q('#guideAction'),title=q('#guideTitle'),detail=q('#guideDetail'),steps=q('#guideSteps');
var FORM_LABEL={path:'FORM I · TRACE',update:'FORM II · SHIFT',span:'FORM III · ECHO'};
function setSteps(labels,active){var nodes=steps.children;for(var i=0;i<3;i++){nodes[i].textContent=labels[i]||'';nodes[i].className=i===active?'on':i<active?'past':''}}
function setGuide(f,a,t,d,labels,active){guideForm.textContent=FORM_LABEL[f]||'BETWEEN FORMS';action.textContent=a;title.textContent=t;detail.textContent=d;setSteps(labels||['OBSERVE','HOLD','ACT'],active==null?-1:active)}
function setInteractiveState(mode,f){app.setAttribute('data-input-mode',mode);if(f)app.setAttribute('data-biy-form',f);if(!dpad)return;var show=mode==='path';dpad.setAttribute('aria-hidden',show?'false':'true');if('inert' in dpad)dpad.inert=!show;dpad.classList.toggle('biy20-hidden',!show)}
function refresh(){var p=phaseText(),f=form(),mode=uiMode();setInteractiveState(mode,f);if(isDistractor())return setGuide('span','TAP THE LARGER ORB','Hold the memory. Answer only this small interruption.','The remembered cells are unchanged.',['SEE','HOLD','RECALL'],1);if(reveal&&reveal.classList.contains('on')){var ok=reveal.classList.contains('win');return setGuide(f,'WATCH ONLY',ok?'The pattern held.':'The pattern drifted.','See what happened. The next trial begins on its own.',['OBSERVE','TRANSFORM','RESPOND'],3)}if(p==='move'||p==='commit')return setGuide('path','SWIPE OR TAP AN ARROW','Trace the hidden route.','One deliberate gesture is one move. There is no undo.',['SEE','VEIL','TRACE'],2);if(p==='update')return setGuide('update','WATCH ONLY','Move only the shown rune in your mind.','Every other rune stays exactly where it was.',['SEE','SHIFT','PLACE'],1);if(p==='place')return setGuide('update','TAP A CELL','Place the shown rune where it ended.','Tap one empty final cell. Swipes do nothing here.',['SEE','SHIFT','PLACE'],2);if(p==='remember')return setGuide('span','WATCH ONLY','Take in this glowing location.','Keep its place and its order.',['SEE','HOLD','RECALL'],0);if(p==='recall')return setGuide('span','TAP A CELL','Return the remembered locations in order.','One tap per location. Swipes do nothing here.',['SEE','HOLD','RECALL'],2);if(p==='study'){var m=studyMode();if(m==='path')return setGuide('path','WATCH ONLY','Read the world once.','Hero. Goal. Walls. Movers. Nothing else matters.',['SEE','VEIL','TRACE'],0);if(m==='update')return setGuide('update','WATCH ONLY','Take in every rune and its place.','The next instruction changes only one rune.',['SEE','SHIFT','PLACE'],0);if(m==='span')return setGuide('span','WATCH ONLY','Take in the glowing location.','You will return to it after the interruption.',['SEE','HOLD','RECALL'],0)}setGuide(f,'WATCH ONLY','Between forms.','The next memory operation will announce itself before you act.',['OBSERVE','HOLD','ACT'],-1)}
installDoctrine();installVersionStamp();var obs=new MutationObserver(function(){requestAnimationFrame(refresh);installDoctrine();installVersionStamp()});obs.observe(phase,{childList:true,characterData:true,subtree:true});obs.observe(grid,{childList:true,subtree:true});if(dist)obs.observe(dist,{attributes:true,attributeFilter:['class']});if(reveal)obs.observe(reveal,{attributes:true,attributeFilter:['class']});
var TAP_MAX=24,SWIPE_MIN=36,AXIS_DOMINANCE=1.18,SUPPRESS_MS=700;var active=null,dispatching=false,lastProgrammaticTarget=null,lastProgrammaticAt=0;
function closest(el,sel){return el&&el.closest?el.closest(sel):null}function gameplayTarget(el){return closest(el,'.dir')||closest(el,'.cell')||closest(el,'.dotbtn')}function pointInStage(el){return !!closest(el,'#stage')}function flash(el){if(!el)return;var c=closest(el,'.cell')||el;c.classList.remove('biy20-pick');void c.offsetWidth;c.classList.add('biy20-pick');setTimeout(function(){c.classList.remove('biy20-pick')},150)}function coreActivate(el){if(!el||el.disabled)return false;dispatching=true;lastProgrammaticTarget=el;lastProgrammaticAt=performance.now();try{el.click()}finally{dispatching=false}flash(el);return true}function dirButton(d){return dpad&&dpad.querySelector('.dir[data-dir="'+d+'"]')}function swipeDir(dx,dy){var ax=Math.abs(dx),ay=Math.abs(dy);if(Math.max(ax,ay)<SWIPE_MIN)return null;if(ax>ay*AXIS_DOMINANCE)return dx>0?'R':'L';if(ay>ax*AXIS_DOMINANCE)return dy>0?'D':'U';return null}function sameTapTarget(a,b,sel){var x=closest(a,sel),y=closest(b,sel);return x&&x===y?x:null}function pointerRelevant(e){if(!app.classList.contains('playing'))return false;var mode=uiMode();if(mode==='interrupt')return !!closest(e.target,'.dotbtn');if(mode==='tap')return !!closest(e.target,'.cell');if(mode==='path')return pointInStage(e.target)||!!closest(e.target,'.dir');return false}
document.addEventListener('pointerdown',function(e){if(!pointerRelevant(e)||active)return;e.preventDefault();e.stopPropagation();active={id:e.pointerId,x:e.clientX,y:e.clientY,target:e.target,mode:uiMode()};try{if(e.target.setPointerCapture)e.target.setPointerCapture(e.pointerId)}catch(_){}},true);document.addEventListener('pointerup',function(e){if(!active||e.pointerId!==active.id)return;var a=active;active=null;e.preventDefault();e.stopPropagation();var dx=e.clientX-a.x,dy=e.clientY-a.y,distance=Math.hypot(dx,dy);if(a.mode==='interrupt'){var orb=sameTapTarget(a.target,e.target,'.dotbtn');if(orb&&distance<=TAP_MAX)coreActivate(orb);return}if(a.mode==='tap'){var cell=sameTapTarget(a.target,e.target,'.cell');if(cell&&distance<=TAP_MAX)coreActivate(cell);return}if(a.mode==='path'){var dir=sameTapTarget(a.target,e.target,'.dir');if(dir&&distance<=TAP_MAX){coreActivate(dir);return}var d=swipeDir(dx,dy);if(d&&pointInStage(a.target))coreActivate(dirButton(d))}},true);document.addEventListener('pointercancel',function(e){if(active&&e.pointerId===active.id)active=null},true);
function stopLegacyTouch(e){if(!app.classList.contains('playing'))return;if(pointInStage(e.target)||closest(e.target,'.dir')||closest(e.target,'.dotbtn')){e.preventDefault();e.stopImmediatePropagation()}}document.addEventListener('touchstart',stopLegacyTouch,{capture:true,passive:false});document.addEventListener('touchmove',stopLegacyTouch,{capture:true,passive:false});document.addEventListener('touchend',stopLegacyTouch,{capture:true,passive:false});document.addEventListener('touchcancel',stopLegacyTouch,{capture:true,passive:false});document.addEventListener('click',function(e){if(dispatching)return;var t=gameplayTarget(e.target);if(!t||!app.classList.contains('playing'))return;var now=performance.now();if(t===lastProgrammaticTarget&&now-lastProgrammaticAt<SUPPRESS_MS){e.preventDefault();e.stopImmediatePropagation();return}if(e.isTrusted&&uiMode()!=='watch'){e.preventDefault();e.stopImmediatePropagation()}},true);document.addEventListener('keydown',function(e){if(e.repeat&&/^(ArrowUp|ArrowDown|ArrowLeft|ArrowRight|w|a|s|d)$/i.test(e.key)){e.preventDefault();e.stopImmediatePropagation()}},true);
window.__BIY_V20__={version:VERSION,thresholds:{tap:TAP_MAX,swipe:SWIPE_MIN,axisDominance:AXIS_DOMINANCE},form:form,uiMode:uiMode,refresh:refresh,swipeDir:swipeDir};refresh();console.info('[Blind Is You v2.0] memory grammar + pointer input active');
})();
