(function(){'use strict';
var phase=document.getElementById('phase'),grid=document.getElementById('grid'),app=document.getElementById('app'),dist=document.getElementById('distractor'),reveal=document.getElementById('reveal');
if(!phase||!grid||!app)return;
var guide=document.createElement('div');guide.id='turnGuide';guide.className='turn-guide';guide.setAttribute('aria-live','polite');guide.innerHTML='<div class="guide-icon" aria-hidden="true"></div><div id="guidePips" class="guide-pips">v1.1</div><div id="guideKicker" class="guide-kicker">READY</div><div id="guideTitle" class="guide-title">Watch the board</div><div id="guideDetail" class="guide-detail">The rule for this step will always be here.</div>';
var top=document.querySelector('.topbar');top.parentNode.insertBefore(guide,top.nextSibling);
var kicker=document.getElementById('guideKicker'),title=document.getElementById('guideTitle'),detail=document.getElementById('guideDetail');
function set(k,t,d){kicker.textContent=k;title.textContent=t;detail.textContent=d}
function modeStudy(){if(grid.querySelector('.avatar'))return'path';if(grid.querySelector('.token'))return'update';if(grid.querySelector('.memory-dot'))return'span';return''}
function refresh(){var p=(phase.textContent||'').trim().toLowerCase();if(dist&&dist.classList.contains('on'))return set('SPAN · INTERRUPT','Tap the larger orb','Answer this tiny task while keeping the remembered cell in mind.');if(reveal&&reveal.classList.contains('on'))return set('RESULT',reveal.classList.contains('win')?'Correct':'See the final board','The next trial begins automatically.');if(p==='move')return set('PATH · RECALL','Recreate the route','Swipe on the board or tap one direction per step. No undo. Speed does not matter.');if(p==='update')return set('UPDATE · MENTAL MOVE','Move only the shown rune one cell','Keep every other rune where it is. Do this move in your head.');if(p==='place')return set('UPDATE · PLACE','Tap the cell where this rune ended','Tap one empty grid cell for the rune shown above. Do not swipe. Each cell can be used once.');if(p==='remember')return set('SPAN · REMEMBER','Remember this glowing cell','Keep its position in order. A quick size choice comes next.');if(p==='recall')return set('SPAN · RECALL','Tap the remembered cells in order','Start with the first cell you saw. One tap per location. Speed does not matter.');if(p==='study'){var m=modeStudy();if(m==='path')return set('PATH · STUDY','Memorize the route','Remember the hero, the flag, and the walls. Do not move yet.');if(m==='update')return set('UPDATE · STUDY','Remember every rune','Memorize where every rune starts. Next they will move only in your head.');if(m==='span')return set('SPAN · REMEMBER','Remember this glowing cell','Keep this location in mind through the interruption.');}set('GET READY','Watch the board','The instruction changes before every action.');}
var obs=new MutationObserver(function(){requestAnimationFrame(refresh)});obs.observe(phase,{childList:true,characterData:true,subtree:true});obs.observe(grid,{childList:true,subtree:true});if(dist)obs.observe(dist,{attributes:true,attributeFilter:['class']});if(reveal)obs.observe(reveal,{attributes:true,attributeFilter:['class']});
var lastMove=0,lockMs=175;function gateMove(e){if(!app.classList.contains('playing'))return true;var t=Date.now();if(t-lastMove<lockMs){e.preventDefault();e.stopImmediatePropagation();return false}lastMove=t;return true}
document.addEventListener('keydown',function(e){if(!/^(ArrowUp|ArrowDown|ArrowLeft|ArrowRight|w|a|s|d)$/i.test(e.key))return;if(e.repeat||!gateMove(e)){e.preventDefault();e.stopImmediatePropagation()}},true);
document.addEventListener('click',function(e){if(!app.classList.contains('playing'))return;var dir=e.target.closest&&e.target.closest('.dir');var cell=e.target.closest&&e.target.closest('.cell');if(dir&&!gateMove(e))return;if(cell){cell.classList.remove('v11-pick');void cell.offsetWidth;cell.classList.add('v11-pick');setTimeout(function(){cell.classList.remove('v11-pick')},230)}},true);
refresh();console.info('[BIY 1.1.1] mobile placement hotfix active');
})();
