from pathlib import Path
src=Path('blind-is-you/index.html')
out=src
lines=src.read_text().splitlines()
new=[]
for line in lines:
    if '<body data-version="0.2">' in line:
        line=line.replace('data-version="0.2"','data-version="0.3"')
    if line.startswith("var VERSION='0.2';"):
        line="var VERSION='0.3';"
    elif line.startswith("var STORAGE_ATTEMPTS="):
        line="var STORAGE_ATTEMPTS='biy_attempts_v1', STORAGE_HASHES='biy_hashes_v1', STORAGE_SEQS='biy_seqs_v1', STORAGE_STATE='biy_staircase_v2', STORAGE_SESSIONS='biy_sessions_v3', SESSION_TRIALS=25, BOOTSTRAP_REPS=1000;"
    elif line.startswith("var audioCtx=null"):
        line="var audioCtx=null,current=null,sessionId='',trialInSession=0,phaseName='idle',studyTimer=null,revealTimer=null,delayTimer=null,firstMoveAt=0,commitStartedAt=0,inputMoves=[],successStreak=0,moverAnimTimer=null,sessionSamples=[],trialsSincePathIncrease=0,sessionMaxPathLength=0,selfTestPassed=false;"
    elif line.startswith('function generateCandidate(params,seed,maxPathTries)'):
        line="function generateCandidate(params,seed,maxPathTries){var n=params.gridSize,limit=maxPathTries||360;for(var tr=0;tr<limit;tr++){var trialSeed=(seed+Math.imul(tr,2654435761))>>>0,rng=mulberry32(trialSeed),path=carveComplexPath(n,params.pathLength,rng,1);if(!path)continue;var solution=pathToMoves(path);if(!complexityPass(solution))throw new Error('Path-complexity assertion failed before uniqueness');var alts=enumerateAlternatives(n,path,8000);if(alts.length>8000)continue;var hit=solveWallHittingSet(alts,8);if(!hit)continue;var structuralCount=hit.length,actual=Math.max(params.wallCount,structuralCount);if(actual>8)continue;hit=addDecorativeWalls(n,path,hit,actual,rng);var walls=wallKeysToPoints(hit);if(allWallsOnOneEdge(walls,n))continue;var bfs=shortestPathInfo(n,path[0],path[path.length-1],walls);if(!bfs||bfs.dist!==params.pathLength||bfs.count!==1)continue;var finalSolution=pathToMoves(bfs.path);if(!complexityPass(finalSolution))throw new Error('Path-complexity assertion failed after uniqueness');var movers=makeMovers(params,rng,n,walls,path[0],path[path.length-1]),candidate={params:cloneParams(params),seed:trialSeed,start:copy(path[0]),flag:copy(path[path.length-1]),walls:walls,actualWallCount:actual,solution:finalSolution,path:bfs.path,movers:movers,generationAttempts:tr+1,alternatePathsRejected:alts.length,structuralWallCount:structuralCount};if(movers.length!==params.movers||simulate(candidate,finalSolution).moverCollision)continue;return candidate}return null}"
    elif line.startswith('function generateBoard(params,diagnostics)'):
        line=line.replace('[BIY v0.2]','[BIY v0.3]')
    elif line.startswith('function classifyError(') or line.startswith('function classifyErrorAt('):
        new.extend([
"function firstDivergenceAt(entered,optimal){for(var i=0;i<Math.max(entered.length,optimal.length);i++)if(entered[i]!==optimal[i])return i;return null}",
"function sliceEqual(a,as,ae,b,bs,be){if(ae-as!==be-bs)return false;for(var i=0;i<ae-as;i++)if(a[as+i]!==b[bs+i])return false;return true}",
"function classifyErrorAt(entered,optimal,firstDiv,pathLength){if(firstDiv===null)return{errorType:null,ratio:null};var L=optimal.length,ratio=firstDiv/pathLength,wrong=entered[firstDiv];if(firstDiv+1<L&&wrong===optimal[firstDiv+1]&&entered[firstDiv+1]===optimal[firstDiv])return{errorType:'transposition',ratio:ratio};if(sliceEqual(entered,firstDiv,Math.max(firstDiv,entered.length-1),optimal,firstDiv+1,L))return{errorType:'omission',ratio:ratio};if(sliceEqual(entered,firstDiv+1,entered.length,optimal,firstDiv,Math.max(firstDiv,L-1)))return{errorType:'intrusion',ratio:ratio};if(firstDiv>0&&wrong===entered[firstDiv-1])return{errorType:'perseveration',ratio:ratio};for(var j=firstDiv+2;j<L;j++)if(optimal[j]===wrong)return{errorType:'anticipation',ratio:ratio};if(firstDiv===0)return{errorType:'encoding',ratio:0};return{errorType:'random',ratio:ratio}}",
"function migrateAttemptClassifications(){var attempts=loadJSON(STORAGE_ATTEMPTS,[]),changed=0;for(var i=0;i<attempts.length;i++){var r=attempts[i];if(!Array.isArray(r.movesEntered)||!Array.isArray(r.optimalMoves))continue;var fd=firstDivergenceAt(r.movesEntered,r.optimalMoves),typed=classifyErrorAt(r.movesEntered,r.optimalMoves,fd,Number(r.pathLength)||r.optimalMoves.length);if(r.errorType!==typed.errorType){if(typeof r.legacyErrorType==='undefined')r.legacyErrorType=r.errorType;changed++}r.firstDivergenceIndex=fd;r.errorType=typed.errorType;r.divergencePositionRatio=typed.ratio;r.classifierVersion='0.3'}if(changed){saveJSON(STORAGE_ATTEMPTS,attempts);console.info('[BIY v0.3] reclassified',changed,'stored attempts with serial-order precedence')}return changed}",
        ])
        continue
    elif line.startswith('function logAttempt(win)'):
        line="function logAttempt(win){var attempts=loadJSON(STORAGE_ATTEMPTS,[]),firstDiv=firstDivergenceAt(inputMoves,current.solution),typed=classifyErrorAt(inputMoves,current.solution,firstDiv,current.params.pathLength),rec={ts:new Date().toISOString(),sessionId:sessionId,gridSize:current.params.gridSize,wallCount:current.actualWallCount,pathLength:current.params.pathLength,exposureMs:current.params.exposureMs,movers:current.movers.length,delayMs:current.params.delayMs,interference:current.params.interference,seed:current.seed,movesEntered:inputMoves.slice(),optimalMoves:current.solution.slice(),result:win?'win':'loss',firstDivergenceIndex:firstDiv,errorType:typed.errorType,legacyErrorType:null,classifierVersion:'0.3',divergencePositionRatio:typed.ratio,timeToFirstMoveMs:firstMoveAt?firstMoveAt-commitStartedAt:null,totalInputMs:commitStartedAt?Date.now()-commitStartedAt:null,generationAttempts:current.generationAttempts||null,version:VERSION};attempts.push(rec);if(attempts.length>5000)attempts=attempts.slice(attempts.length-5000);saveJSON(STORAGE_ATTEMPTS,attempts);rememberBoard(current);rememberSequence(current.solution.join(''));sessionSamples.push(rec);return rec}"
    elif line.startswith('function updateStaircase(win)'):
        line="function updateStaircase(win){if(win){successStreak++;if(successStreak>=2){difficultyIndex=clamp(difficultyIndex+1,0,ladder.length-1);successStreak=0}}else{difficultyIndex=clamp(difficultyIndex-1,0,ladder.length-1);successStreak=0}var after=ladder[difficultyIndex];if(after.pathLength>sessionMaxPathLength){sessionMaxPathLength=after.pathLength;trialsSincePathIncrease=0}else trialsSincePathIncrease++;if(trialsSincePathIncrease>=6&&sessionMaxPathLength<12&&difficultyIndex<ladder.length-1){difficultyIndex++;after=ladder[difficultyIndex];console.warn('[BIY v0.3] forced staircase increment after 6 trials without a new pathLength maximum',after);if(after.pathLength>sessionMaxPathLength){sessionMaxPathLength=after.pathLength;trialsSincePathIncrease=0}}saveJSON(STORAGE_STATE,{index:difficultyIndex,version:VERSION})}"
    elif line.startswith('function sessionValidity()'):
        new.extend([
"function sigmoid(z){if(z>35)return 1;if(z<-35)return 0;return 1/(1+Math.exp(-z))}",
"function fitLogisticThreshold(samples){if(!samples.length)return{threshold:null,reason:'no trials'};var seen={},i;for(i=0;i<samples.length;i++)seen[samples[i].pathLength]=1;if(Object.keys(seen).length<4)return{threshold:null,reason:'fewer than 4 distinct pathLength values',distinctPathLengths:Object.keys(seen).length};var mean=0;for(i=0;i<samples.length;i++)mean+=samples[i].pathLength;mean/=samples.length;var a=0,b=0;for(var it=0;it<40;it++){var g0=0,g1=0,h00=1e-6,h01=0,h11=1e-6;for(i=0;i<samples.length;i++){var x=samples[i].pathLength-mean,y=samples[i].result==='win'?1:0,p=sigmoid(a+b*x),w=Math.max(1e-6,p*(1-p));g0+=y-p;g1+=(y-p)*x;h00+=w;h01+=w*x;h11+=w*x*x}var det=h00*h11-h01*h01;if(Math.abs(det)<1e-12)break;var da=(g0*h11-g1*h01)/det,db=(g1*h00-g0*h01)/det;a+=da;b+=db;if(Math.abs(da)+Math.abs(db)<1e-7)break}if(!isFinite(a)||!isFinite(b)||Math.abs(b)<1e-6)return{threshold:null,reason:'flat logistic fit',intercept:a,slope:b};var threshold=mean-a/b;if(!isFinite(threshold))return{threshold:null,reason:'non-finite threshold',intercept:a,slope:b};if(b>=0)return{threshold:null,reason:'non-decreasing logistic fit',rawThreshold:threshold,intercept:a,slope:b};return{threshold:threshold,reason:null,intercept:a,slope:b}}",
"function hashString(s){var h=2166136261>>>0;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}",
"function percentile(sorted,p){if(!sorted.length)return null;var x=(sorted.length-1)*p,lo=Math.floor(x),hi=Math.ceil(x);if(lo===hi)return sorted[lo];return sorted[lo]+(sorted[hi]-sorted[lo])*(x-lo)}",
"function bootstrapThreshold(samples,reps,seed){var rng=mulberry32(seed>>>0),vals=[];for(var r=0;r<reps;r++){var boot=[];for(var i=0;i<samples.length;i++)boot.push(samples[randint(rng,samples.length)]);var fit=fitLogisticThreshold(boot);if(fit.threshold!==null&&isFinite(fit.threshold)&&Math.abs(fit.threshold)<100)vals.push(fit.threshold)}vals.sort(function(a,b){return a-b});return{low:vals.length>=100?percentile(vals,.025):null,high:vals.length>=100?percentile(vals,.975):null,validReplicates:vals.length,reps:reps}}",
"function directChanceBaselines(samples){var pSum=0,pN=0,tSum=0,tN=0;for(var s=0;s<samples.length;s++){var o=samples[s].optimalMoves||[];for(var i=1;i<o.length;i++){pN++;if(o[i-1]!==o[i])pSum+=1/3}for(i=0;i<o.length-1;i++){tN++;if(o[i+1]!==o[i])tSum+=1/3}}return{chancePerseverationRate:pN?pSum/pN:null,chanceTranspositionRate:tN?tSum/tN:null}}",
"function nullClassifierRates(samples){var names=['transposition','omission','intrusion','perseveration','anticipation','encoding','random'],counts={},total=0,ds=['U','D','L','R'];for(var n=0;n<names.length;n++)counts[names[n]]=0;for(var s=0;s<samples.length;s++){var o=samples[s].optimalMoves||[];for(var i=0;i<o.length;i++)for(var d=0;d<ds.length;d++){if(ds[d]===o[i])continue;var e=o.slice();e[i]=ds[d];var typ=classifyErrorAt(e,o,i,o.length).errorType;if(typ&&typeof counts[typ]!=='undefined')counts[typ]++;total++}}var rates={};for(n=0;n<names.length;n++)rates[names[n]]=total?counts[names[n]]/total:0;return rates}",
"function observedErrorRates(samples){var names=['transposition','omission','intrusion','perseveration','anticipation','encoding','random'],counts={},losses=0,rates={};for(var n=0;n<names.length;n++)counts[names[n]]=0;for(var i=0;i<samples.length;i++){if(samples[i].result==='win')continue;losses++;if(typeof counts[samples[i].errorType]!=='undefined')counts[samples[i].errorType]++}for(n=0;n<names.length;n++)rates[names[n]]=losses?counts[names[n]]/losses:0;return{rates:rates,losses:losses}}",
"function analyzeSession(samples,id){var trimmed=samples.slice(Math.min(4,samples.length)),fit=fitLogisticThreshold(trimmed),boot={low:null,high:null,validReplicates:0,reps:BOOTSTRAP_REPS};if(fit.threshold!==null)boot=bootstrapThreshold(trimmed,BOOTSTRAP_REPS,hashString(id||'session'));var direct=directChanceBaselines(samples),nullRates=nullClassifierRates(samples),obs=observedErrorRates(samples),compare={},names=['transposition','omission','intrusion','perseveration','anticipation','encoding','random'];for(var i=0;i<names.length;i++){var k=names[i],or=obs.rates[k],cr=nullRates[k];compare[k]={observedRate:or,chanceRate:cr,status:or>cr?'above-chance':'n.s.'}}return{warmupDiscarded:Math.min(4,samples.length),analysisTrials:trimmed.length,threshold50:fit.threshold,thresholdCI95Low:boot.low,thresholdCI95High:boot.high,thresholdFitReason:fit.reason,logisticSlope:fit.slope,bootstrapValidReplicates:boot.validReplicates,bootstrapReps:boot.reps,chancePerseverationRate:direct.chancePerseverationRate,chanceTranspositionRate:direct.chanceTranspositionRate,errorTypeObservedVsChance:compare,losses:obs.losses}}",
"function sessionValidity(){if(!sessionSamples.length)return null;var seen={},grids={},max=0;for(var i=0;i<sessionSamples.length;i++){var r=sessionSamples[i];seen[r.pathLength]=1;grids[r.gridSize]=1;if(r.pathLength>max)max=r.pathLength}var d=Object.keys(seen).length,g=Object.keys(grids).length,valid=d>=3,analysis=analyzeSession(sessionSamples,sessionId),summary={sessionId:sessionId,trials:sessionSamples.length,distinctPathLengths:d,maxPathLength:max,gridSizeChanged:g>1,valid:valid,ts:new Date().toISOString(),analysisVersion:'0.3',analysis:analysis};var all=loadJSON(STORAGE_SESSIONS,[]);all.push(summary);if(all.length>500)all=all.slice(all.length-500);saveJSON(STORAGE_SESSIONS,all);if(valid)console.info('[BIY v0.3] SESSION VALID',summary);else console.error('SESSION INVALID — no escalation',summary);if(analysis.threshold50===null)console.warn('[BIY v0.3] no 50% threshold:',analysis.thresholdFitReason);else console.info('[BIY v0.3] fitted P(win)=0.5 threshold',analysis.threshold50.toFixed(2),'moves; bootstrap 95% CI',analysis.thresholdCI95Low===null?'unresolved':analysis.thresholdCI95Low.toFixed(2),analysis.thresholdCI95High===null?'unresolved':analysis.thresholdCI95High.toFixed(2),'(wide intervals are expected at ~25 trials)');console.info('[BIY v0.3] mandatory chance baselines',{chanceTranspositionRate:analysis.chanceTranspositionRate,chancePerseverationRate:analysis.chancePerseverationRate});console.table(analysis.errorTypeObservedVsChance);return summary}",
        ])
        continue
    elif line.startswith('function startSession()'):
        line="function startSession(){if(!selfTestPassed)return;initAudio();try{if(screen.orientation&&screen.orientation.lock)screen.orientation.lock('portrait').catch(function(){})}catch(e){}welcome.className='screen';sessionEnd.className='screen';app.className='playing';trialInSession=0;successStreak=0;trialsSincePathIncrease=0;sessionSamples=[];sessionMaxPathLength=ladder[difficultyIndex].pathLength;sessionId='s_'+Date.now().toString(36);nextTrial()}"
    elif line.startswith('function nextTrial()'):
        line=line.replace('[BIY v0.2]','[BIY v0.3]')
    elif line.startswith('function exportCSV()'):
        line="function exportCSV(){var a=loadJSON(STORAGE_ATTEMPTS,[]);if(!a.length){alert('No attempts recorded yet.');return}var cols=['ts','sessionId','gridSize','wallCount','pathLength','exposureMs','movers','delayMs','interference','seed','movesEntered','optimalMoves','result','firstDivergenceIndex','errorType','legacyErrorType','classifierVersion','divergencePositionRatio','timeToFirstMoveMs','totalInputMs','generationAttempts','version'];function esc(v){if(Array.isArray(v))v=v.join('');if(v===null||typeof v==='undefined')v='';v=String(v).replace(/\"/g,'\"\"');return '\"'+v+'\"'}var rows=[cols.join(',')];for(var i=0;i<a.length;i++){var row=[];for(var j=0;j<cols.length;j++)row.push(esc(a[i][cols[j]]));rows.push(row.join(','))}var blob=new Blob([rows.join('\\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='blind-is-you-attempts-'+new Date().toISOString().slice(0,10)+'.csv';document.body.appendChild(link);link.click();document.body.removeChild(link);setTimeout(function(){URL.revokeObjectURL(url)},500)}"
    elif line.startswith('function runSelfTest()'):
        line=line.replace('[BIY v0.2]','[BIY v0.3]')
    elif line.startswith('window.__BIY_DEBUG__='):
        line="window.__BIY_DEBUG__={version:VERSION,ladder:ladder,pathMetrics:pathMetrics,complexityPass:complexityPass,pathToMoves:pathToMoves,carveComplexPath:carveComplexPath,shortestPathInfo:shortestPathInfo,generateCandidate:generateCandidate,classifyErrorAt:classifyErrorAt,fitLogisticThreshold:fitLogisticThreshold,analyzeSession:analyzeSession,reclassifyStoredAttempts:migrateAttemptClassifications,generateBoard:function(p){return generateBoard(p||cloneParams(ladder[difficultyIndex]),true)},getSessions:function(){return loadJSON(STORAGE_SESSIONS,[])},getState:function(){return{difficultyIndex:difficultyIndex,params:cloneParams(ladder[difficultyIndex]),phase:phaseName,current:current,inputMoves:inputMoves.slice(),selfTestPassed:selfTestPassed}}};"
    elif line.strip()=='bind();runSelfTest();':
        line="migrateAttemptClassifications();bind();runSelfTest();"
    line=line.replace('[BIY v0.2]','[BIY v0.3]')
    new.append(line)

out.write_text('\n'.join(new)+'\n')
print(out)
